export type Locale = "en" | "es";

const en = {
  title: "Database dependency migration · Whetstone",
  description:
    "Trace PostgreSQL dependencies with source evidence and review migration hazards before execution.",
  skip: "Skip to content",
  home: "Whetstone database dependency migration home",
  nav: {
    workflow: "How it works",
    examples: "Examples",
    install: "Install",
    label: "Main navigation",
  },
  preferences: {
    language: "Language",
    dark: "Switch to dark mode",
    light: "Switch to light mode",
  },
  hero: {
    eyebrow: "POSTGRESQL / AGENT SKILL",
    lead: "Know what",
    accent: "depends on it.",
    end: "Before you migrate.",
    body: "A column changes. A foreign key, a view, a query might follow. Trace those connections and review your proposal with the source evidence attached.",
    examples: "Explore the examples",
    install: "Install the skill",
    foot: "LOCAL ANALYSIS · REVIEW-ONLY PLANS",
  },
  study: {
    label: "IMPACT STUDY / 001",
    backed: "Source-backed",
    proposal: "PROPOSED CHANGE",
    root: "COLUMN / ROOT",
    column: "COLUMN",
    view: "VIEW",
    parsed: "PARSED",
    direct: "direct dependents",
    affected: "potentially affected",
    hint: "Hover, focus, or tap a column to follow its trace.",
    all: "Selected reverse paths. Arrows point to dependencies.",
    fk: "Foreign key reference",
    query: "Parsed query reference",
    foot: "Selected paths from the shipped ecommerce model. Potential impact requires review.",
  },
  scope: [
    "PostgreSQL DDL + catalogs",
    "SQL repository references",
    "Evidence in every artifact",
  ],
  workflow: {
    eyebrow: "01 / HOW IT WORKS",
    lead: "A schema change is",
    accent: "a dependency question.",
    body: "Start with your sources. Build one validated model. Follow the impact, then produce artifacts for human review.",
    stages: [
      {
        key: "INSPECT",
        title: "Your sources",
        body: "PostgreSQL DDL, SQL files, or a supplied catalog snapshot.",
        file: "schema.sql + app/*.sql",
      },
      {
        key: "VALIDATE",
        title: "One canonical model",
        body: "Stable object IDs, typed edges, source hashes, and explicit unknowns.",
        file: "schema.dbdep.json",
      },
      {
        key: "TRACE + REVIEW",
        title: "The change in context",
        body: "Reverse dependency paths, SQL hazards, and transaction boundaries.",
        file: "impact + migration.sql",
      },
      {
        key: "GENERATE",
        title: "Evidence you can inspect",
        body: "A dependency report and a phased plan for review. Migrations are never applied.",
        file: "HTML · Markdown · JSON",
      },
    ],
    foot: "One model also exports Mermaid and DOT diagrams.",
    replay: "Replay the flow",
    skill: "Read the skill",
  },
  examples: {
    eyebrow: "02 / TRY A REAL SCENARIO",
    lead: "The question first.",
    accent: "The full report when you need it.",
    body: "Three reproducible examples, generated by the CLI. Open the interactive diagrams in their own page.",
    open: "Open HTML report",
    source: "View source on GitHub",
    note: "Reports and CLI artifacts are in English. Each HTML report is self-contained and works offline.",
    cards: [
      {
        category: "ECOMMERCE",
        title: "What depends on a customer ID?",
        body: "A BIGINT-to-UUID proposal reaches foreign keys, a summary view, and SQL consumers.",
        question: "customers.id → uuid",
        limitation: "UUID mapping needs operational review.",
      },
      {
        category: "ANALYTICS",
        title: "How far does a table change reach?",
        body: "Follow recorded PostgreSQL dependencies from orders into a chain of downstream views.",
        question: "orders → summary → revenue",
        limitation: "Catalog evidence does not cover every runtime consumer.",
      },
      {
        category: "INDEX REVIEW",
        title: "Can this index proposal run as written?",
        body: "Review concurrent index creation inside a transaction and potential locking hazards.",
        question: "CREATE INDEX CONCURRENTLY",
        limitation: "Lock duration and downtime are not measured.",
      },
    ],
  },
  install: {
    eyebrow: "03 / YOUR WORKSPACE",
    lead: "Give your agent",
    accent: "the dependency map.",
    body: "Use the repository as an Agent Skill or run the Python toolkit directly. Inputs and reports stay in your workspace.",
    steps: [
      {
        title: "Get the repository.",
        body: "Clone or download the checkout from GitHub.",
      },
      {
        title: "Install the toolkit.",
        body: "Run the command from the repository root with Python 3.11+.",
      },
      {
        title: "Connect your agent.",
        body: "Copy or symlink the repository into your agent's skill directory, then reload the agent.",
      },
    ],
    folders: "Skill folder locations",
    folderNote:
      "Project-level directories also work. See the README for setup details.",
    root: "FROM THE REPOSITORY ROOT",
    install: "INSTALL",
    commands: "INSPECT → VALIDATE → RENDER",
    copyInstall: "Copy Python install command",
    copyCommands: "Copy inspect validate and render commands",
    output: "OUTPUT",
  },
  copy: { idle: "Copy", done: "Copied", failed: "Select to copy" },
  limits: {
    eyebrow: "KNOW THE BOUNDARIES",
    lead: "Evidence first.",
    accent: "Keep the unknowns visible.",
    docs: "Read coverage and limitations",
    entries: [
      {
        title: "Analysis stays local.",
        body: "The toolkit writes local artifacts and never applies migrations. Live discovery requires an explicit request and uses read-only catalog queries.",
      },
      {
        title: "Runtime coverage is incomplete.",
        body: "Dynamic SQL, ORM queries, routine bodies, and nested column scopes have partial or unknown coverage. DML and backfill semantics are outside the hazard engine.",
      },
      {
        title: "A path is a reason to investigate.",
        body: "Potential impact does not prove failure, an exact CASCADE deletion closure, or downtime. The HTML viewer displays up to 350 nodes, 40 paths, and 16 steps per path. CLI artifacts retain the full analysis.",
      },
    ],
  },
  footer: {
    line: "DATABASE DEPENDENCY MIGRATION",
    source: "Source",
    skill: "Skill definition",
    notices: "Third-party notices",
  },
};

export type Copy = typeof en;

const es: Copy = {
  title: "Dependencias y migraciones de bases de datos · Whetstone",
  description:
    "Rastrea dependencias de PostgreSQL con evidencia de las fuentes y revisa riesgos de migración antes de ejecutar.",
  skip: "Saltar al contenido",
  home: "Inicio de Whetstone, dependencias y migraciones de bases de datos",
  nav: {
    workflow: "Cómo funciona",
    examples: "Ejemplos",
    install: "Instalar",
    label: "Navegación principal",
  },
  preferences: {
    language: "Idioma",
    dark: "Activar modo oscuro",
    light: "Activar modo claro",
  },
  hero: {
    eyebrow: "POSTGRESQL / AGENT SKILL",
    lead: "Descubre qué",
    accent: "depende de ello.",
    end: "Antes de migrar.",
    body: "Cambia una columna. Una clave foránea, una vista o una consulta podrían verse afectadas. Rastrea esas conexiones y revisa tu propuesta con la evidencia de las fuentes.",
    examples: "Explorar los ejemplos",
    install: "Instalar la skill",
    foot: "ANÁLISIS LOCAL · PLANES PARA REVISIÓN",
  },
  study: {
    label: "ESTUDIO DE IMPACTO / 001",
    backed: "Con evidencia",
    proposal: "CAMBIO PROPUESTO",
    root: "COLUMNA / RAÍZ",
    column: "COLUMNA",
    view: "VISTA",
    parsed: "ANALIZADO",
    direct: "dependientes directos",
    affected: "posiblemente afectados",
    hint: "Pasa el cursor, enfoca o toca una columna para seguir su conexión.",
    all: "Rutas inversas seleccionadas. Las flechas apuntan a las dependencias.",
    fk: "Referencia de clave foránea",
    query: "Referencia de consulta analizada",
    foot: "Rutas del modelo de ecommerce incluido. El impacto potencial requiere revisión.",
  },
  scope: [
    "DDL y catálogos de PostgreSQL",
    "Referencias SQL del repositorio",
    "Evidencia en cada artefacto",
  ],
  workflow: {
    eyebrow: "01 / CÓMO FUNCIONA",
    lead: "Cambiar un esquema es",
    accent: "preguntar por sus dependencias.",
    body: "Empieza con las fuentes. Construye un modelo validado. Rastrea el impacto y genera artefactos para revisión humana.",
    stages: [
      {
        key: "INSPECCIONAR",
        title: "Tus fuentes",
        body: "DDL de PostgreSQL, archivos SQL o una captura del catálogo.",
        file: "schema.sql + app/*.sql",
      },
      {
        key: "VALIDAR",
        title: "Un modelo canónico",
        body: "Identificadores estables, conexiones tipadas, hashes de las fuentes e incertidumbre explícita.",
        file: "schema.dbdep.json",
      },
      {
        key: "RASTREAR + REVISAR",
        title: "El cambio en contexto",
        body: "Rutas inversas de dependencias, riesgos SQL y límites de transacción.",
        file: "impact + migration.sql",
      },
      {
        key: "GENERAR",
        title: "Evidencia que puedes revisar",
        body: "Un informe de dependencias y un plan por fases para revisión. Las migraciones nunca se ejecutan.",
        file: "HTML · Markdown · JSON",
      },
    ],
    foot: "El mismo modelo también exporta diagramas Mermaid y DOT.",
    replay: "Repetir el recorrido",
    skill: "Leer la skill",
  },
  examples: {
    eyebrow: "02 / EXPLORA UN CASO REAL",
    lead: "Primero, la pregunta.",
    accent: "El informe completo, cuando lo necesites.",
    body: "Tres ejemplos reproducibles, generados por la CLI. Abre los diagramas interactivos en una página aparte.",
    open: "Abrir informe HTML",
    source: "Ver código en GitHub",
    note: "Los informes y artefactos de la CLI están en inglés. Cada informe HTML es independiente y funciona sin conexión.",
    cards: [
      {
        category: "ECOMMERCE",
        title: "¿Qué depende del ID de un cliente?",
        body: "Una propuesta de BIGINT a UUID alcanza claves foráneas, una vista de resumen y consultas SQL.",
        question: "customers.id → uuid",
        limitation: "El mapeo a UUID requiere revisión operativa.",
      },
      {
        category: "ANALÍTICA",
        title: "¿Hasta dónde llega un cambio de tabla?",
        body: "Sigue las dependencias registradas en PostgreSQL desde orders hasta sus vistas derivadas.",
        question: "orders → summary → revenue",
        limitation: "El catálogo no cubre todos los consumidores en ejecución.",
      },
      {
        category: "REVISIÓN DE ÍNDICES",
        title: "¿Puede ejecutarse esta propuesta de índice?",
        body: "Revisa la creación concurrente de un índice dentro de una transacción y posibles bloqueos.",
        question: "CREATE INDEX CONCURRENTLY",
        limitation:
          "No se mide la duración de bloqueos ni la indisponibilidad.",
      },
    ],
  },
  install: {
    eyebrow: "03 / TU ESPACIO DE TRABAJO",
    lead: "Dale a tu agente",
    accent: "el mapa de dependencias.",
    body: "Usa el repositorio como Agent Skill o ejecuta directamente el toolkit de Python. Tus fuentes e informes quedan en tu espacio de trabajo.",
    steps: [
      {
        title: "Obtén el repositorio.",
        body: "Clona o descarga el repositorio desde GitHub.",
      },
      {
        title: "Instala el toolkit.",
        body: "Ejecuta el comando desde la raíz del repositorio con Python 3.11+.",
      },
      {
        title: "Conecta tu agente.",
        body: "Copia o enlaza el repositorio al directorio de skills de tu agente y vuelve a cargarlo.",
      },
    ],
    folders: "Ubicación de las carpetas de skills",
    folderNote:
      "También funcionan los directorios del proyecto. Consulta el README para la configuración.",
    root: "DESDE LA RAÍZ DEL REPOSITORIO",
    install: "INSTALAR",
    commands: "INSPECCIONAR → VALIDAR → GENERAR",
    copyInstall: "Copiar comando de instalación de Python",
    copyCommands: "Copiar comandos de inspección, validación y generación",
    output: "SALIDA",
  },
  copy: { idle: "Copiar", done: "Copiado", failed: "Selecciona para copiar" },
  limits: {
    eyebrow: "CONOCE LOS LÍMITES",
    lead: "Primero, la evidencia.",
    accent: "La incertidumbre siempre visible.",
    docs: "Leer cobertura y limitaciones",
    entries: [
      {
        title: "El análisis es local.",
        body: "El toolkit genera artefactos locales y nunca ejecuta migraciones. La consulta en vivo requiere una petición explícita y usa consultas de solo lectura al catálogo.",
      },
      {
        title: "La cobertura en ejecución es incompleta.",
        body: "SQL dinámico, consultas ORM, cuerpos de rutinas y columnas en ámbitos anidados tienen cobertura parcial o desconocida. La semántica de DML y del relleno de datos queda fuera del motor de riesgos.",
      },
      {
        title: "Una ruta es un motivo para investigar.",
        body: "El impacto potencial no prueba fallos, el alcance exacto de un borrado CASCADE ni indisponibilidad. El visor HTML muestra hasta 350 nodos, 40 rutas y 16 pasos por ruta. Los artefactos de la CLI conservan el análisis completo.",
      },
    ],
  },
  footer: {
    line: "DEPENDENCIAS Y MIGRACIONES DE BASES DE DATOS",
    source: "Código",
    skill: "Definición de la skill",
    notices: "Avisos de terceros",
  },
};

export const copies: Record<Locale, Copy> = { en, es };
